export default function Head() {
	return (
		<>
			<title>Wordeľ</title>
			<meta
				content='width=device-width, initial-scale=1'
				name='viewport'
			/>
			<meta
				name='description'
				content='Generated by create next app'
			/>
			<meta
				name='theme-color'
				content='#181818'
			/>
			<link
				rel='icon'
				type='image/png'
				href='/favicon-96x96.png'
				sizes='96x96'
			/>
			<link
				rel='icon'
				type='image/svg+xml'
				href='/favicon.svg'
			/>
			<link
				rel='shortcut icon'
				href='/favicon.ico'
			/>
			<link
				rel='apple-touch-icon'
				sizes='180x180'
				href='/apple-touch-icon.png'
			/>
			<link
				rel='manifest'
				href='/site.webmanifest'
			/>
		</>
	);
}
