export default function Head() {
	return (
		<>
			<title>Wordeľ</title>
			<meta content='width=device-width, initial-scale=1' name='viewport' />
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' type='image/svg+xml' href='/wordel_logo.png' />
			<meta name='theme-color' content='#181818' />
		</>
	);
}
